name: Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      attestations: write

    defaults:
      run:
        working-directory: plugin

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - run: mvn clean package

      - uses: actions/upload-artifact@v4
        with:
          name: oneheart
          path: plugin/target/*.jar

      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: plugin/target/*.jar
